using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public class AutoUIBuilder
{
    [MenuItem("Tools/2단계: 플레이어 UI 시스템 자동 생성! (HP바 + 아이템)")]
    public static void BuildPlayerUI()
    {
        // 1. 기존 캔버스가 있으면 중복 생성 방지
        if (GameObject.Find("PlayerUI_Canvas_AutoGenerated") != null)
        {
            Debug.LogWarning("이미 생성된 플레이어 UI가 있습니다!");
            return;
        }

        // 2. 최상위 Canvas 생성
        GameObject canvasObj = new GameObject("PlayerUI_Canvas_AutoGenerated");
        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 50; // 모든 카메라 렌더링보다 앞에 오도록 설정

        CanvasScaler scaler = canvasObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(720, 960);
        scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.Expand;

        canvasObj.AddComponent<GraphicRaycaster>();

        // 3. UI 기본 리소스 불러오기
        DefaultControls.Resources uiResources = new DefaultControls.Resources();
        uiResources.standard = AssetDatabase.GetBuiltinExtraResource<Sprite>("UI/Skin/UISprite.psd");
        uiResources.background = AssetDatabase.GetBuiltinExtraResource<Sprite>("UI/Skin/Background.psd");

        // 4. 체력바(HP Bar Slider) 생성
        GameObject sliderObj = DefaultControls.CreateSlider(uiResources);
        sliderObj.name = "HealthBar_Slider";
        sliderObj.transform.SetParent(canvasObj.transform, false);
        
        RectTransform sliderRt = sliderObj.GetComponent<RectTransform>();
        sliderRt.anchorMin = new Vector2(0, 1); // 좌측 상단 기준
        sliderRt.anchorMax = new Vector2(0, 1);
        sliderRt.pivot = new Vector2(0, 1);
        sliderRt.anchoredPosition = new Vector2(20, -20); // 화면 안쪽으로 살짝 여백
        sliderRt.sizeDelta = new Vector2(250, 30);

        Slider slider = sliderObj.GetComponent<Slider>();
        slider.interactable = false; // 마우스로 조작 불가능하게
        slider.transition = Selectable.Transition.None;
        
        Image fillImage = slider.fillRect.GetComponent<Image>();

        // 4-1. 체력바 안에 들어갈 숫자 Text 생성
        GameObject hpTextObj = DefaultControls.CreateText(uiResources);
        hpTextObj.name = "HP_Numbers_Text";
        hpTextObj.transform.SetParent(sliderObj.transform, false);
        
        RectTransform hpRt = hpTextObj.GetComponent<RectTransform>();
        hpRt.anchorMin = new Vector2(0, 0); // 꽉 차게
        hpRt.anchorMax = new Vector2(1, 1);
        hpRt.offsetMin = Vector2.zero;
        hpRt.offsetMax = Vector2.zero;
        
        Text hpText = hpTextObj.GetComponent<Text>();
        hpText.alignment = TextAnchor.MiddleCenter;
        hpText.color = Color.white;
        hpText.fontStyle = FontStyle.Bold;

        // 5. 남은 아이템(대쉬 횟수) Text 생성
        GameObject dashTextObj = DefaultControls.CreateText(uiResources);
        dashTextObj.name = "ItemDash_Text";
        dashTextObj.transform.SetParent(canvasObj.transform, false);
        
        RectTransform dashRt = dashTextObj.GetComponent<RectTransform>();
        dashRt.anchorMin = new Vector2(0, 1); // HP바 아래쪽 정렬
        dashRt.anchorMax = new Vector2(0, 1);
        dashRt.pivot = new Vector2(0, 1);
        dashRt.anchoredPosition = new Vector2(20, -60);
        dashRt.sizeDelta = new Vector2(300, 40);

        Text dashText = dashTextObj.GetComponent<Text>();
        dashText.alignment = TextAnchor.MiddleLeft;
        dashText.color = Color.cyan;
        dashText.fontSize = 24;
        dashText.fontStyle = FontStyle.Bold;

        // 6. 작성한 전용 PlayerUI 동기화 스크립트 붙이고 연결
        PlayerUI uiScript = canvasObj.AddComponent<PlayerUI>();
        uiScript.healthSlider = slider;
        uiScript.hpText = hpText;
        uiScript.fillImage = fillImage;
        uiScript.itemText = dashText;

        Debug.Log("🎉 [완료] HP바 및 아이템 UI가 씬에 완벽히 구축되었습니다!");
    }
}
