using UnityEditor;
using UnityEngine;
using UnityEngine.UI;

public class AutoUIBuilder
{
    [MenuItem("Tools/2단계: 플레이어 UI 시스템 자동 생성! (HP바 + 에너지)")]
    public static void BuildPlayerUI()
    {
        // 1. 기존 캔버스가 있으면 중복 생성 방지
        if (GameObject.Find("PlayerUI_Canvas_AutoGenerated") != null)
        {
            Debug.LogWarning("이미 생성된 플레이어 UI가 있습니다! 삭제 후 다시 실행해주세요.");
            return;
        }

        // 2. 최상위 Canvas 생성
        GameObject canvasObj = new GameObject("PlayerUI_Canvas_AutoGenerated");
        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 50;

        CanvasScaler scaler = canvasObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1200);
        scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.Expand;

        canvasObj.AddComponent<GraphicRaycaster>();

        DefaultControls.Resources uiRes = new DefaultControls.Resources();
        uiRes.standard = AssetDatabase.GetBuiltinExtraResource<Sprite>("UI/Skin/UISprite.psd");
        uiRes.background = AssetDatabase.GetBuiltinExtraResource<Sprite>("UI/Skin/Background.psd");

        // ===================================================================
        // 3. 전체 바 컨테이너 (화면 상단 좌측)
        // ===================================================================
        GameObject containerObj = new GameObject("HUD_Bar_Container");
        containerObj.transform.SetParent(canvasObj.transform, false);
        RectTransform containerRt = containerObj.AddComponent<RectTransform>();
        containerRt.anchorMin = new Vector2(0, 1);
        containerRt.anchorMax = new Vector2(0, 1);
        containerRt.pivot = new Vector2(0, 1);
        containerRt.anchoredPosition = new Vector2(30, -25);
        containerRt.sizeDelta = new Vector2(620, 40);

        // ===================================================================
        // 4. HP 바 (왼쪽, 큰 바) - 숫자 없이 바만!
        // ===================================================================
        GameObject hpBgObj = new GameObject("HP_Bar_Background");
        hpBgObj.transform.SetParent(containerObj.transform, false);
        Image hpBgImg = hpBgObj.AddComponent<Image>();
        hpBgImg.color = new Color(0.06f, 0.06f, 0.06f, 0.92f);
        RectTransform hpBgRt = hpBgObj.GetComponent<RectTransform>();
        hpBgRt.anchorMin = new Vector2(0, 0);
        hpBgRt.anchorMax = new Vector2(0, 1);
        hpBgRt.pivot = new Vector2(0, 0.5f);
        hpBgRt.anchoredPosition = new Vector2(0, 0);
        hpBgRt.sizeDelta = new Vector2(420, 0);

        // HP 슬라이더
        GameObject hpSliderObj = DefaultControls.CreateSlider(uiRes);
        hpSliderObj.name = "HP_Slider";
        hpSliderObj.transform.SetParent(hpBgObj.transform, false);

        // 핸들 제거
        Transform handleArea = hpSliderObj.transform.Find("Handle Slide Area");
        if (handleArea != null) Object.DestroyImmediate(handleArea.gameObject);

        Slider hpSlider = hpSliderObj.GetComponent<Slider>();
        hpSlider.interactable = false;
        hpSlider.transition = Selectable.Transition.None;
        hpSlider.handleRect = null;

        RectTransform hpSliderRt = hpSliderObj.GetComponent<RectTransform>();
        hpSliderRt.anchorMin = Vector2.zero;
        hpSliderRt.anchorMax = Vector2.one;
        hpSliderRt.offsetMin = new Vector2(4, 4);
        hpSliderRt.offsetMax = new Vector2(-4, -4);

        // 트랙 배경
        Transform bgTransform = hpSliderObj.transform.Find("Background");
        if (bgTransform != null)
        {
            Image bgImage = bgTransform.GetComponent<Image>();
            if (bgImage != null) bgImage.color = new Color(0.12f, 0.12f, 0.12f, 0.5f);
        }

        // HP Fill 색상
        Image hpFillImage = hpSlider.fillRect.GetComponent<Image>();
        hpFillImage.color = new Color(0.2f, 0.95f, 0.1f, 1f);

        // ===================================================================
        // 5. 구분선 (빨간 마커)
        // ===================================================================
        GameObject dividerObj = new GameObject("Divider_Marker");
        dividerObj.transform.SetParent(containerObj.transform, false);
        Image dividerImg = dividerObj.AddComponent<Image>();
        dividerImg.color = new Color(1f, 0.15f, 0.15f, 1f);
        RectTransform dividerRt = dividerObj.GetComponent<RectTransform>();
        dividerRt.anchorMin = new Vector2(0, 0.15f);
        dividerRt.anchorMax = new Vector2(0, 0.85f);
        dividerRt.pivot = new Vector2(0.5f, 0.5f);
        dividerRt.anchoredPosition = new Vector2(425, 0);
        dividerRt.sizeDelta = new Vector2(10, 0);

        // 구분선 위 동그란 점
        GameObject dotObj = new GameObject("Dot");
        dotObj.transform.SetParent(containerObj.transform, false);
        Image dotImg = dotObj.AddComponent<Image>();
        dotImg.color = new Color(1f, 0.2f, 0.2f, 1f);
        RectTransform dotRt = dotObj.GetComponent<RectTransform>();
        dotRt.anchorMin = new Vector2(0, 0.5f);
        dotRt.anchorMax = new Vector2(0, 0.5f);
        dotRt.anchoredPosition = new Vector2(425, 0);
        dotRt.sizeDelta = new Vector2(14, 14);

        // ===================================================================
        // 6. 에너지 바 (오른쪽, 작은 바) - 숫자 없이 바만!
        // ===================================================================
        GameObject energyBgObj = new GameObject("Energy_Bar_Background");
        energyBgObj.transform.SetParent(containerObj.transform, false);
        Image energyBgImg = energyBgObj.AddComponent<Image>();
        energyBgImg.color = new Color(0.06f, 0.06f, 0.06f, 0.92f);
        RectTransform energyBgRt = energyBgObj.GetComponent<RectTransform>();
        energyBgRt.anchorMin = new Vector2(0, 0);
        energyBgRt.anchorMax = new Vector2(0, 1);
        energyBgRt.pivot = new Vector2(0, 0.5f);
        energyBgRt.anchoredPosition = new Vector2(437, 0);
        energyBgRt.sizeDelta = new Vector2(183, 0);

        // 에너지 슬라이더
        GameObject energySliderObj = DefaultControls.CreateSlider(uiRes);
        energySliderObj.name = "Energy_Slider";
        energySliderObj.transform.SetParent(energyBgObj.transform, false);

        Transform eHandleArea = energySliderObj.transform.Find("Handle Slide Area");
        if (eHandleArea != null) Object.DestroyImmediate(eHandleArea.gameObject);

        Slider energySlider = energySliderObj.GetComponent<Slider>();
        energySlider.interactable = false;
        energySlider.transition = Selectable.Transition.None;
        energySlider.handleRect = null;

        RectTransform energySliderRt = energySliderObj.GetComponent<RectTransform>();
        energySliderRt.anchorMin = Vector2.zero;
        energySliderRt.anchorMax = Vector2.one;
        energySliderRt.offsetMin = new Vector2(4, 4);
        energySliderRt.offsetMax = new Vector2(-4, -4);

        Transform eBgTransform = energySliderObj.transform.Find("Background");
        if (eBgTransform != null)
        {
            Image eBgImage = eBgTransform.GetComponent<Image>();
            if (eBgImage != null) eBgImage.color = new Color(0.12f, 0.12f, 0.12f, 0.5f);
        }

        // 에너지 Fill 색상 (황록 → 노란색 그라데이션 느낌)
        Image energyFillImage = energySlider.fillRect.GetComponent<Image>();
        energyFillImage.color = new Color(0.6f, 1f, 0.05f, 1f);

        // ===================================================================
        // 7. PlayerUI 스크립트 부착 및 연결 (텍스트 없이 바만!)
        // ===================================================================
        PlayerUI uiScript = canvasObj.AddComponent<PlayerUI>();
        uiScript.healthSlider = hpSlider;
        uiScript.hpText = null;            // 숫자 텍스트 없음
        uiScript.fillImage = hpFillImage;
        uiScript.highHpColor = new Color(0.2f, 0.95f, 0.1f);
        uiScript.lowHpColor = new Color(1f, 0.2f, 0.1f);

        uiScript.energySlider = energySlider;
        uiScript.energyText = null;        // 숫자 텍스트 없음
        uiScript.energyFillImage = energyFillImage;
        uiScript.highEnergyColor = new Color(0.6f, 1f, 0.05f);
        uiScript.lowEnergyColor = new Color(1f, 0.85f, 0f);

        Undo.RegisterCreatedObjectUndo(canvasObj, "Create Player HUD UI");

        Debug.Log("🎉 [완료] 젠레스 존 제로 스타일 HP바 + 에너지 게이지 HUD 생성 완료! (숫자 없음, 바만 표시)");
    }
}
