using System.Collections;
using UnityEngine;

/// <summary>
/// 역경직(Hit Stop) 시스템: TimeScale을 순간적으로 0으로 만들어 찰진 타격감을 연출합니다.
/// 씬에 없더라도 자동으로 생성되어 씬 전체에 걸쳐 유지됩니다.
/// </summary>
public class HitStop : MonoBehaviour
{
    private static HitStop _instance;

    public static HitStop instance
    {
        get
        {
            if (_instance == null)
            {
                // 씬 내부에서 기존 오브젝트 탐색
                _instance = FindObjectOfType<HitStop>();

                if (_instance == null)
                {
                    // 없을 시 DontDestroyOnLoad 속성을 가진 빈 오브젝트에 자동 부착하여 생성
                    GameObject go = new GameObject("HitStop_AutoGenerated");
                    _instance = go.AddComponent<HitStop>();
                    DontDestroyOnLoad(go);
                    Debug.Log("⚙️ [HitStop] 씬 내에 역경직 매니저가 없어 자동으로 생성했습니다 (DontDestroyOnLoad).");
                }
            }
            return _instance;
        }
    }

    private void Awake()
    {
        if (_instance == null)
        {
            _instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else if (_instance != this)
        {
            Destroy(gameObject);
        }
    }

    /// <summary>
    /// 역경직을 발동합니다. duration 동안 게임 시간이 멈췄다가 복구됩니다.
    /// </summary>
    /// <param name="duration">역경직 지속 시간 (실제 시간 기준, 초)</param>
    public void Do(float duration)
    {
        // 이미 역경직 중이면 중복 실행하지 않음
        if (Time.timeScale == 0f) return;
        StartCoroutine(HitStopRoutine(duration));
    }

    private IEnumerator HitStopRoutine(float duration)
    {
        Time.timeScale = 0f;
        yield return new WaitForSecondsRealtime(duration);
        Time.timeScale = 1f;
    }
}
