using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>
/// 게임 전체에서 작동하는 글로벌 일시정지 매니저입니다.
/// 각 씬마다 오브젝트를 배치할 필요 없이, 게임 기동 시 자동으로 DontDestroyOnLoad 오브젝트로 생성됩니다.
/// </summary>
public class PauseManager : MonoBehaviour
{
    private static PauseManager instance;
    private bool isPaused = false;
    private GameObject pauseCanvasObj;

    // 일시정지를 작동시킬 게임플레이 씬 목록 (허브나 메인메뉴에서는 ESC 기본 동작 유지를 위해 제외)
    private readonly string[] gameplayScenes = { "game_Scene", "Stage2_Scene", "Stage3_Scene" };

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void Initialize()
    {
        if (instance == null)
        {
            GameObject go = new GameObject("PauseManager_AutoGenerated");
            instance = go.AddComponent<PauseManager>();
            DontDestroyOnLoad(go);
            Debug.Log("⚙️ [PauseManager] 글로벌 일시정지 매니저가 자동으로 기동되었습니다 (DontDestroyOnLoad).");
        }
    }

    private void Update()
    {
        // ESC 키가 눌렸을 때
        if (Input.GetKeyDown(KeyCode.Escape))
        {
            // 현재 활성화된 씬이 일시정지가 필요한 게임플레이 씬인지 체크
            if (IsGameplayScene())
            {
                TogglePause();
            }
        }
    }

    /// <summary>
    /// 현재 씬이 일시정지를 지원하는 인게임 플레이 씬인지 검사합니다.
    /// </summary>
    private bool IsGameplayScene()
    {
        string currentScene = SceneManager.GetActiveScene().name;
        foreach (string sceneName in gameplayScenes)
        {
            if (currentScene == sceneName)
            {
                return true;
            }
        }
        return false;
    }

    /// <summary>
    /// 일시정지 상태를 토글합니다.
    /// </summary>
    public void TogglePause()
    {
        isPaused = !isPaused;

        if (isPaused)
        {
            PauseGame();
        }
        else
        {
            ResumeGame();
        }
    }

    private void PauseGame()
    {
        Time.timeScale = 0f;
        CreatePauseUI();
        Debug.Log("⏸️ 게임이 일시정지되었습니다.");
    }

    public void ResumeGame()
    {
        isPaused = false;
        Time.timeScale = 1f;
        
        if (pauseCanvasObj != null)
        {
            Destroy(pauseCanvasObj);
            pauseCanvasObj = null;
        }
        Debug.Log("▶️ 게임이 재개되었습니다.");
    }

    /// <summary>
    /// 허브 씬으로 복귀하고 일시정지를 해제합니다.
    /// </summary>
    public void ReturnToHub()
    {
        ResumeGame();
        SceneManager.LoadScene("Hub_Scene");
        Debug.Log("🏠 일시정지 메뉴를 통해 허브 씬으로 복귀합니다.");
    }

    /// <summary>
    /// 일시정지 UI 화면을 절차적 코드로 생성합니다. (UI 프리팹 에셋 의존 없음)
    /// </summary>
    private void CreatePauseUI()
    {
        if (pauseCanvasObj != null) return;

        // 1. Canvas 생성
        pauseCanvasObj = new GameObject("PauseCanvas");
        Canvas canvas = pauseCanvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 99999; // 최상단 레이어 보장

        CanvasScaler scaler = pauseCanvasObj.AddComponent<CanvasScaler>();
        scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution = new Vector2(1920, 1080);
        
        pauseCanvasObj.AddComponent<GraphicRaycaster>();

        // 2. 어두운 배경 패널 생성 (Dim Background)
        GameObject bgObj = new GameObject("DimBackground");
        bgObj.transform.SetParent(pauseCanvasObj.transform, false);
        Image bgImg = bgObj.AddComponent<Image>();
        bgImg.color = new Color(0f, 0f, 0f, 0.65f); // 65% 불투명 블랙

        RectTransform bgRect = bgImg.GetComponent<RectTransform>();
        bgRect.anchorMin = Vector2.zero;
        bgRect.anchorMax = Vector2.one;
        bgRect.offsetMin = Vector2.zero;
        bgRect.offsetMax = Vector2.one;

        // 3. 타이틀 텍스트 생성 (PAUSED)
        GameObject titleObj = new GameObject("PauseTitleText");
        titleObj.transform.SetParent(pauseCanvasObj.transform, false);
        Text titleText = titleObj.AddComponent<Text>();
        titleText.font = Resources.GetBuiltinResource<Font>("Arial.ttf");
        titleText.text = "PAUSED";
        titleText.fontSize = 70;
        titleText.fontStyle = FontStyle.Bold;
        titleText.color = new Color(0.9f, 0.9f, 0.9f, 1f);
        titleText.alignment = TextAnchor.MiddleCenter;

        Shadow titleShadow = titleObj.AddComponent<Shadow>();
        titleShadow.effectColor = Color.black;
        titleShadow.effectDistance = new Vector2(3f, -3f);

        RectTransform titleRect = titleObj.GetComponent<RectTransform>();
        titleRect.anchorMin = new Vector2(0.5f, 0.65f);
        titleRect.anchorMax = new Vector2(0.5f, 0.65f);
        titleRect.pivot = new Vector2(0.5f, 0.5f);
        titleRect.anchoredPosition = Vector2.zero;
        titleRect.sizeDelta = new Vector2(600, 150);

        // 4. 버튼들을 감싸는 레이아웃 컨테이너 생성
        GameObject containerObj = new GameObject("ButtonsContainer");
        containerObj.transform.SetParent(pauseCanvasObj.transform, false);
        
        RectTransform containerRect = containerObj.AddComponent<RectTransform>();
        containerRect.anchorMin = new Vector2(0.5f, 0.4f);
        containerRect.anchorMax = new Vector2(0.5f, 0.4f);
        containerRect.pivot = new Vector2(0.5f, 0.5f);
        containerRect.anchoredPosition = Vector2.zero;
        containerRect.sizeDelta = new Vector2(400, 250);

        // 5. 계속하기 (Resume) 버튼 생성
        CreateButton(containerObj.transform, "ResumeButton", "계속하기", new Vector2(0, 50), () => ResumeGame());

        // 6. 허브로 (Return to Hub) 버튼 생성
        CreateButton(containerObj.transform, "HubButton", "허브로 돌아가기", new Vector2(0, -50), () => ReturnToHub());
    }

    /// <summary>
    /// 일시정지 메뉴 내부에 배치할 버튼을 동적으로 빌드합니다.
    /// </summary>
    private void CreateButton(Transform parent, string name, string labelText, Vector2 pos, UnityEngine.Events.UnityAction onClickAction)
    {
        GameObject btnObj = new GameObject(name);
        btnObj.transform.SetParent(parent, false);

        // 이미지 및 버튼 컴포넌트 추가
        Image btnImg = btnObj.AddComponent<Image>();
        btnImg.color = new Color(0.2f, 0.2f, 0.2f, 0.85f); // 어두운 회색 버튼

        Button btn = btnObj.AddComponent<Button>();
        btn.onClick.AddListener(onClickAction);

        // 마우스 호버 효과를 위한 컬러 블록 설정
        ColorBlock cb = btn.colors;
        cb.normalColor = new Color(0.2f, 0.2f, 0.2f, 0.85f);
        cb.highlightedColor = new Color(0.35f, 0.35f, 0.35f, 1f);
        cb.pressedColor = new Color(0.15f, 0.15f, 0.15f, 1f);
        btn.colors = cb;

        RectTransform btnRect = btnObj.GetComponent<RectTransform>();
        btnRect.sizeDelta = new Vector2(300, 60);
        btnRect.anchoredPosition = pos;

        // 버튼 글씨 생성
        GameObject txtObj = new GameObject("Text");
        txtObj.transform.SetParent(btnObj.transform, false);
        Text btnText = txtObj.AddComponent<Text>();
        btnText.font = Resources.GetBuiltinResource<Font>("Arial.ttf");
        btnText.text = labelText;
        btnText.fontSize = 24;
        btnText.color = Color.white;
        btnText.alignment = TextAnchor.MiddleCenter;

        RectTransform txtRect = txtObj.GetComponent<RectTransform>();
        txtRect.anchorMin = Vector2.zero;
        txtRect.anchorMax = Vector2.one;
        txtRect.offsetMin = Vector2.zero;
        txtRect.offsetMax = Vector2.one;
    }
}
